version: '3'
services:
  frontend:
    build: medisell
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    environment:
      - VITE_REACT_APP_DOMAIN=http://localhost:8000/

  backend:
    build: backend
    ports:
      - "8000:8000" # Map host port 8080 to container port 8080
    environment:
      - PORT=8000
      - MONGO_URI=mongodb+srv://bill:goldengold@medisell.uhzwqm8.mongodb.net/medisell